### PR TITLE
build(deps): bump all golang dependencies

### PR DESCRIPTION
**Pull request by AtomicFS**
manually run:
```
go get -u
go mod tidy
```

### CODE REVIEW

**Comment by AtomicFS** [comment]
Looks maybe like issue in dagger? No idea.

**Comment by MDr164** [comment]
`go get -u` without a package (aka updating all of them) is prone to cause issues because it will update the indirect deps as well regardless of which version was pulled in by the direct deps. If the indirect ones get too new their API might change and therefore break code in the direct deps. I always refrain from a global `go get -u` and rather just call it only on the direct deps. So https://github.com/9elements/firmware-action/pull/482 should be enough to update our Go deps properly.

**Comment by AtomicFS** [comment]
Fair enough. I was just too lazy to debug #482, so I wanted to try this approach just in case it would work.

**Comment by AtomicFS** [comment]
Closed in favor of #482

**Pull request closed without merging**
