### PR TITLE
fix(docker): edk2-stable202408 missing submodule

### LINKED ISSUE #385: edk2 container build for `edk2-stable202408` fails
The Zeex/subhook upstream is gone https://github.com/tianocore/edk2/issues/6398

### PR DESCRIPTION
**Pull request by AtomicFS**
replace edk2-stable202408 with edk2-stable202408.01 to fix the missing git submodule

fixes #385

### CODE REVIEW

**Comment by AtomicFS** [comment]
running out of disk-space ... yet again :(

**Comment by AtomicFS** [comment]
I don't know why sometimes it can find `make` and sometimes not. Maybe #394 will fix it.

**Comment by AtomicFS** [comment]
what the heck, now another edk2 build is failing #387

**Comment by AtomicFS** [comment]
UPDATE on #397: I can clone Edk2 repo with all of the submodules without any issue. The problem happens when executed inside the dagger CI, this also happens when run locally with
```
go-task containers:build:container-edk2-stable202008
```

**Comment by MDr164** [comment]
> UPDATE on #397: I can clone Edk2 repo with all of the submodules without any issue. The problem happens when executed inside the dagger CI, this also happens when run locally with
> 
> ```
> go-task containers:build:container-edk2-stable202008
> ```

I can reproduce the failure locally as well. Maybe a typo somewhere?

**Comment by AtomicFS** [comment]
From my experiments it seems that the `Edk2` submodules, on this specific commits, do not play well with [shallow init](https://github.com/9elements/firmware-action/pull/392/commits/641910cb8b7292ca8b50a9043f2d77272cd4a4c1). When I remove the `shallow init` it magically works again.

**Comment by AtomicFS** [comment]
OK, I made ugly-ass fix with IF ELSE condition.

If `edk2-stable202008` then do not shallow clone git submodules. I also left salty commit message.

**Review by MDr164 — APPROVED** [review]
Not really a fan of the fix but I also don't have any better idea so

**Comment by AtomicFS** [comment]
I do not like the fix either, hence the salty commit message

**Pull request merged**
